import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProvider, Heading } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Your Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <ChakraProvider>
          <Heading
            color="white"
            bgColor="#afeeee"
            textAlign="center"
            h={20}
            size="lg"
            textShadow="1px 1px #0000cd"
            p={5}
          >
            Your Todo by Next.js
          </Heading>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
